### ISSUE TITLE
Failed to find a suitable Github repository URL, sorry!

### ISSUE THREAD

**Issue by matthiasbeyer** [jaxbot/github-issues.vim#120]
Why does this happen?

I have the following remotes:

```
github  git@github.com:matthiasbeyer/....git <-- my repo, the main repo
someuser1 https://github.com/...
someuser2 https://github.com/...
someuser3 https://github.com/...
```

There is definitely an option missing to tell which remote should be used. `let g:github_upstream_issues` doesn't solve the problem.

**Comment by amerlyq** [comment]
I have confirmed this bug re-appears for credentials in format described in #154.
For all other repos with usual credentials all works as expected.
