### ISSUE TITLE
github-issues.vim requires Python support, sorry :c Error

### ISSUE THREAD

**Issue by sittim** [jaxbot/github-issues.vim#160]
I could not get Python 2 working on my Vim8 installation, so I am getting the `github-issues.vim requires Python support, sorry :c Error`.   So I am wondering if there are any plans to add the Python 3 Support.

**Comment by Fubukimaru** [comment]
If you're using Ubuntu, there are versions of vim compiled with python2 support, e.g. vim-nox-py2. But an upgrade  to python3 would be great.

**Comment by osleg** [comment]
Merged #172, should work with Py3 now, closing this, feel free to reopen if anything goes wrong
